### ISSUE TITLE
Add tests on the consistency of the results of raz_create_posterior

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#103]
raz_create_posterior has a lot of tests, but they are only concerning the shape of the output. We need also to test if the values make sense or not.
I added some of them. @richel, please check if we need more.

**Comment by richelbilderbeek** [comment]
I enjoy the enthusiasm!

@Giappo: this may come unexpected, but it is **against** the TDD literature to add 'tests just to be sure'. The *is* an upper limit to the amount of tests: if a test does not break the code, delete it. Else the test is maintained without benefit and just slows down the project.

The tests make sense, and I will keep them in for now, due to said enthusiasm :+1:

**Comment by richelbilderbeek** [comment]
Close, as I've checked :rainbow:
