### ISSUE TITLE
Make run_razzo save in the project_folder

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/razzo#163]
We need run_razzo to save in the folder we want, ideally the .../razzo_project/results
run_razzo (and therefore pir_run) instead save everything into a temporary folder.
We have to possibilities:
1) (more sloppy) We copy from the temp folder to the folder we want;
2) (cooler) We make pir_run save in the folder specified by the user. Then we call it from razzo in such a way it will save in the folder specified by the user.

**Comment by richelbilderbeek** [comment]
Option 2, the cooler option, is mostly already put in place: within the `razzo_params` (yes, it's big), there a many filenames that can be set to the target folder. 

Most of these filenames are already present, except for the BEAST2 files, which is why 'Specify where the BEAST2 output files are stored', #64, is something I work on after the bigger Issue I work on now (#69).

Keep up the good work :+1:

**Comment by richelbilderbeek** [comment]
When I take a look:

```r
create_parameters_files <- function(
  project_folder_name = getwd(),
  experiment_type = "test"
) {
  # ...
}
```

I feel this is already implemented... :thinking:

**Comment by richelbilderbeek** [comment]
I again feel this is already implemented :rainbow: 

Just closing the Issue and see what happens :grin:
