### ISSUE TITLE
create_fig_1_file produces an empty output on peregrine

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#208]
When running this code, which is part of the first test in `test-create_fig_1_file.R`:

```
filename <- create_fig_1_file(
  project_folder_name = get_razzo_path("razzo_project")
)
```

I get this error:

```
Saving 4.55 x 2.68 in image
Error in ggplot2::as_labeller(q_labels, label_parsed) : 
  object 'label_parsed' not found
Called from: formals(f)
```

**Comment by richelbilderbeek** [comment]
The figure created:

![figure_1](https://user-images.githubusercontent.com/2098230/60255057-4d0f2080-98cf-11e9-85d6-ac8ff4b714e2.png)

Yes, it is indeed empty :-)

**Comment by richelbilderbeek** [comment]
Bug can be found on `develop`:

```
context("test-create_fig_1_file")

test_that("use", {

  skip("Issue #208")

  # Should create 'results/fig_1.png'
  filename <- create_fig_1_file(
    project_folder_name = get_razzo_path("razzo_project")
  )
  
  # ...
})
```

**Comment by Giappo** [comment]
Hi Richel,
I specified ggplot2:: in front of the function. I tested it on peregrine (which is linux, on windows it was already working) and it produces a figure on the Graphics Device but it doesn't save it. The problem is that i get this message:
`Warning message:
In grid.Call.graphics(C_rect, x$x, x$y, x$width, x$height, resolveHJust(x$just,  :
  semi-transparency is not supported on this device: reported only once per page
`
From a quick google search it looks that this has something to do with the (wrong as of now, apparently) usage of Cairo. I remember that you used it already, for pirouette, if I am not wrong. Can it be that using the same strategy now will solve the problem?

**Comment by richelbilderbeek** [comment]
>  I remember that you used it already, for pirouette

I wish that was the case! On `pirouette` I get the same error messages on Peregrine and for it, I haven't solved the problem either...

**Comment by Giappo** [comment]
In any case the problem now is no more that "label_parsed" is not found, but it is something different.
Therefore I change the issue name.

**Comment by richelbilderbeek** [comment]
Doesn't scale the font, but good enough for now...

![ggplot](https://user-images.githubusercontent.com/2098230/61209660-a615eb80-a6fa-11e9-8891-4d720cf0da12.png)

**Comment by richelbilderbeek** [comment]
From a fresh re-run, at 2019-07-15:

![figure_1](https://user-images.githubusercontent.com/2098230/61213935-cfd50f80-a706-11e9-8053-51997bd68a38.png)

Will check if the dsize of the ggplot2 object is specified...

**Comment by richelbilderbeek** [comment]
Locally, it does work:

![figure_1](https://user-images.githubusercontent.com/2098230/61216614-0f532a00-a70e-11e9-90af-872b01a9d281.png)

**Comment by richelbilderbeek** [comment]
Error on Peregrine:

```
xvfb-run Rscript 
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 5 at size 12 could not be loaded
Calls: <Anonymous> ... <Anonymous> -> heightDetails -> heightDetails.text -> grid.Call
In addition: Warning message:
In grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
  X11 used font size 24 when 50 was requested
Execution halted
```

**Comment by richelbilderbeek** [comment]
I'll accept this fails for now...
