### ISSUE TITLE
'raz_create_mbd_tree' should create trees with the expected number of speciation events

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#24]
After fixing #63 ('Fix mbd package')

(note: I just put this here now, as I think we agree on this, else leave a comment below :+1: )

`raz_create_mbd_tree` creates an MBD tree for some parameters.

As far as I can see, I think we'll pick `nu` to have 0/1/2/4 ot 8 expected triggered speciation events. `raz_create_mbd_tree` should only keep those trees that have experienced that number of triggered speciation events.

**Comment by Giappo** [comment]
So the formula we need is just E[n] = nu * t which we have to reverse in case we want to fix nu according to the E[n]. My problem now is: we need to specify that raz_create_mbd_tree can use this E[n] as an argument in place of the standard nu, but this is not allowed by our very strict parameter input scheme. How do we do that???

**Comment by richelbilderbeek** [comment]
I suggest to have a parameter called `n_speciation_events`. From that, we can derive the nu.

**Comment by richelbilderbeek** [comment]
Marked test with: 

```
  skip(
    "TODO: Issue #24: Create trees with expected number of speciation events"
  )
```

@Giappo: I assume this helps you get started on this Issue? If not, let me know.

It requires writing `mbd::mbd_count_n_spec_events` (a function added to the `mbd` package, feel free to use any related name). The function simply counts the number of times there were two speciation events at exactly the same time.

**Comment by Giappo** [comment]
Now there is a function called "raz_create_mbd_tree_events" which creates a tree with a given number of multiple events specified by the argument "nu_events".
In the body of the function the parameter "nu" is replaced by:
new_nu <- nu_events / age
There is a specific test just for this function
@richelbilderbeek feel free to check the tests that are already present and to add more. Now the problem is that this kind of test is really slow. We might consider to add some ribir::is_on_travis() options if we need a long time

**Comment by richelbilderbeek** [comment]
We'll definitely test the function in the 'Launch' phase of the project. For now, I am happy to close this Issue :racehorse:
