### ISSUE TITLE
Create fig 1: separate generative from best

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/razzo#276]
From @rsetienne:

> In the plots I would put the bars of the histrograms next to each other instead of behind each other, for better visibiity.

**Comment by richelbilderbeek** [comment]
@Giappo: I assign you this Issue, as I think you would enjoy it. No worries about the time: I will re-assign to myself when really needing this :+1:

**Comment by Giappo** [comment]
Mmm, I am afraid I might not get this exactly. Can you show me a simple example?

**Comment by richelbilderbeek** [comment]
I think @rsetienne wants this:

![what_rampal_wants](https://user-images.githubusercontent.com/2098230/64619398-4ed28580-d3e2-11e9-9f66-982a872c5ad2.png)

**Comment by Giappo** [comment]
Something like [this](https://bio723-class.github.io/Bio723-book/bio723-book_files/figure-html/unnamed-chunk-120-1.png)?

**Comment by richelbilderbeek** [comment]
Yes :rainbow:

**Comment by Giappo** [comment]
I asked Rampal and one possible option seems to be to draw only the boundaries, leaving blank the inside of the distributions. I will implement it tomorrow.

**Comment by richelbilderbeek** [comment]
> Honestly, even though I completely understand Rampal's argument, I do not believe this is the optimal solution. The looks is not exciting, imho.

Agreed.

> What if we instead break each figure in twelve squares and we separate generative from best?
It will probably suffice to increase the visibility to a decent extent

Sounds like a plan!

> I asked Rampal and one possible option seems to be to draw only the boundaries, leaving blank the inside of the distributions. I will implement it tomorrow.

Cool, good luck :+1:

**Comment by Giappo** [comment]
This is the current state of the figures.
@richelbilderbeek if you think the quality is high enough you can close the issue. Otherwise tell me how you would improve them.
🌈 

![figure_1b](https://user-images.githubusercontent.com/14541948/66771762-64dcd580-eebb-11e9-8d92-cf85e8cc9db7.png)
![figure_1c](https://user-images.githubusercontent.com/14541948/66771763-64dcd580-eebb-11e9-9a81-eaf9c8b8b48a.png)
![figure_1d](https://user-images.githubusercontent.com/14541948/66771764-64dcd580-eebb-11e9-8aec-2ae019b6fb1c.png)
![figure_1a](https://user-images.githubusercontent.com/14541948/66771765-64dcd580-eebb-11e9-93bf-04f1f86ce471.png)

**Comment by richelbilderbeek** [comment]
I think those plots look greatawesome!
